### ISSUE TITLE
The "Packages" search in the new update form errors with: unable to find any packages that match the current query

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1731]
It was reported today that the "Packages" field in the new update form does not work correctly. Instead of offering autocomplete matches, an error message "unable to find any packages that match the current query" appears. It seems that the browser is experiencing a CSRF error.

I was unable to reproduce this error at first, but I found that issuing a hard refresh (ctrl-f5) to my browser enabled me to experience the issue. This leads me to believe that it may be due to JS changes in Bodhi 2.9.0.

**Comment by bowlofeggs** [comment]
One of the issues causing this has been fixed on the packages app, but Bodhi also seems to be double-urlencoding the URL, which is causing an invalid query against packages.

**Comment by bowlofeggs** [comment]
This could be due to the recent switch to a newer version of typeahead, since the JS in question here does seem to use that library:

https://github.com/fedora-infra/bodhi/blob/2.9.0/bodhi/server/static/js/update_form.js#L29-L33

**Comment by bowlofeggs** [comment]
Workaround: the package search is really a user convenience to aid in filling out the nvrs and bugs - you should be able to manually type nvrs and bug numbers in and submit the form as per usual.

**Comment by limburgher** [comment]
I can confirm that this workaround works.

**Comment by bowlofeggs** [comment]
This should be fixed in the upcoming 2.10.0 release:

https://github.com/fedora-infra/bodhi/pull/1744

**Comment by jeremycline** [comment]
I think this is still an issue in 2.10. When creating a new update, both candidate builds and packages can't be searched :(

**Comment by puiterwijk** [comment]
The initial fix showed an error in the server-side config of packages, and this issue is now fixed.

**Comment by puiterwijk** [comment]
(note: users might need to force-refresh their browsers or wait for caches to expire)
