### ISSUE TITLE
Add info how to test update

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/bodhi#2261]
https://bodhi.fedoraproject.org/updates/FEDORA-2018-2a55cd1b82 - from this page it is absolutely unclear how to test the update. How do you know?

**Comment by bowlofeggs** [comment]
We could probably add a template to the page that can fill in Fedora specific items for how to test an update.

In the meantime, you can install an update on Fedora like this:

```
$ sudo dnf upgrade --enablerepo updates-testing --advisory FEDORA-2018-2a55cd1b82
```

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in Bodhi 3.13: #2917.

**Comment by abitrolly** [comment]
Is there a ticket to track deployment of 3.13 to test the implementation?

**Comment by bowlofeggs** [comment]
@abitrolly there's not a ticket for the deployment. I attempted to deploy it on Monday, but hit a [disk space issue](https://pagure.io/fedora-infrastructure/issue/7504). It seems that is resolved now, so I may be able to get it deployed soon.

**Comment by bowlofeggs** [comment]
This fix is now deployed to staging: https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html

It is also available via Copr: https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/

**Comment by abitrolly** [comment]
Not fixed. I don't see any info how to test this update - https://bodhi.stg.fedoraproject.org/updates/FEDORA-MODULAR-2019-a240824f88

**Comment by bowlofeggs** [comment]
@abitrolly ah yes, I forgot that the patch only works for RPM packages. Here's an example RPM update that has the dnf install instructions:

https://bodhi.stg.fedoraproject.org/updates/FEDORA-2019-86217cbcd3

As bodhi now supports four content types, each needs unique instructions for how to test. Rather than reopening this particular ticket, I've created these to track this request for each of those so that it can be tracked and worked on incrementally: #2937, #2938, #2939.

**Comment by abitrolly** [comment]
Screenshot for the history.

![image](https://user-images.githubusercontent.com/8781107/51323372-13610080-1a79-11e9-806b-cb51cc693691.png)
