### ISSUE TITLE
Cannot edit list of builds in an update

### ISSUE THREAD

**Issue by mbooth101** [fedora-infra/bodhi#655]
Hi all, I am unable to edit the list of builds on a bodhi update -- is this intentional? The lotus flower spins for a bit and then stops, but I get no feedback at all (no errors, no success) and when I re-open the update, my edits are gone.

I wanted to add an updated build and add an additional build to an update, but I found it to be impossible, so had to submit two separate additional updates instead.

This is not ideal, since users will be receiving three updates instead of one.

FWIW, the update I tried to edit is this one:
https://bodhi.fedoraproject.org/updates/FEDORA-2015-2ba0ca6444 (currently in testing and was already pushed to testing when I attempted to edit it)

I needed to update and add builds, but instead I had to file these as separate updates:
https://bodhi.fedoraproject.org/updates/FEDORA-2015-1eb7d762a4
https://bodhi.fedoraproject.org/updates/FEDORA-2015-6a7ea97ee8

**Comment by mbooth101** [comment]
This problem is still present!

I am unable to edit this update: https://bodhi.fedoraproject.org/updates/eclipse-xtext-antlr-generator-2.1.1-2.git18383dd.fc23%20antlr32-3.2-11.fc23

Can someone with the correct privileges please remove the antlr32 build and add the the latest, antlr32-3.2-12.fc23 ?

**Comment by ralphbean** [comment]
Unless I'm mistaken, #700 should fix this once it gets deployed.

**Comment by lmacken** [comment]
This issue should hopefully be resolved with the latest version in production. Please re-open if you still hit this problem. Thanks!

https://lists.fedoraproject.org/archives/list/infrastructure%40lists.fedoraproject.org/thread/WJLJGYQYGA5FZJ353GFNNSWLIK5VGWUO/

**Comment by mbooth101** [comment]
BTW, github does not allow re-opening bugs if a repo contributor closes them and this bug IS NOT fixed, please reopen.

I am still unable to edit my updates. You can try this yourself, please try to edit this update: https://bodhi.fedoraproject.org/updates/FEDORA-2015-03f691b1fb

**Comment by lmacken** [comment]
What builds are you trying to add?

**Comment by mbooth101** [comment]
Simply newer builds of the ones that are there and one additional one:

eclipse-xtext-antlr-generator-2.1.1-3.git18383dd.fc23
antlr3-3.5.2-10.fc23
antlr32-3.2-12.fc23

**Comment by lmacken** [comment]
Okay, this should hopefully be fixed now.
